# Week 2 Assignment

## Objectives: import and explore the data set

Familiarise yourself with the data by:

- setting up your working files and folders
- determining the size and shape of the data sets
- loading the data into a DataFrame
- identifying whether there are any missing values 
- determining the vaccination status in Gibraltar by identifying the number of people who:
    
    - are vaccinated
    - have received the first dose
    - have received the second dose

### Prepare workstation

In [2]:
# Import the packages

In [3]:
import pandas as pd
import numpy as np

In [4]:
cases = pd.read_csv('covid_19_uk_cases.csv')
vaccinated = pd.read_csv('covid_19_uk_vaccinated.csv')

In [5]:
cases.dtypes

Province/State               object
Country/Region               object
Lat                         float64
Long                        float64
ISO 3166-1 Alpha 3-Codes     object
Sub-region Name              object
Intermediate Region Code      int64
Date                         object
Deaths                      float64
Cases                       float64
Recovered                   float64
Hospitalised                float64
dtype: object

In [6]:
cases.head()

,Province/State,Country/Region,Lat,Long,ISO 3166-1 Alpha 3-Codes,Sub-region Name,Intermediate Region Code,Date,Deaths,Cases,Recovered,Hospitalised
0,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-22,0.0,0.0,0.0,0.0
1,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-23,0.0,0.0,0.0,0.0
2,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-24,0.0,0.0,0.0,0.0
3,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-25,0.0,0.0,0.0,0.0
4,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-26,0.0,0.0,0.0,0.0

In [7]:
cases.shape

(7584, 12)

In [8]:
vaccinated.dtypes

Province/State               object
Country/Region               object
Lat                         float64
Long                        float64
ISO 3166-1 Alpha 3-Codes     object
Sub-region Name              object
Intermediate Region Code      int64
Date                         object
Vaccinated                    int64
First Dose                    int64
Second Dose                   int64
dtype: object

In [9]:
vaccinated.shape

(7584, 11)

In [10]:
vaccinated.head()

,Province/State,Country/Region,Lat,Long,ISO 3166-1 Alpha 3-Codes,Sub-region Name,Intermediate Region Code,Date,Vaccinated,First Dose,Second Dose
0,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-22,0,0,0
1,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-23,0,0,0
2,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-24,0,0,0
3,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-25,0,0,0
4,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-26,0,0,0

### Check for missing data

Use .isna to check for missing data

In [11]:
# Check cases dataframe for missing data
cases_na = cases[cases.isna().any(axis=1)]

In [12]:
cases_na.shape

(2, 12)

In [13]:
# Check vaccinated DataFrame for missing data
vaccinated_na = vaccinated[vaccinated.isna().any(axis=1)]

In [14]:
vaccinated_na.shape

(0, 11)

In [15]:
cases_na

,Province/State,Country/Region,Lat,Long,ISO 3166-1 Alpha 3-Codes,Sub-region Name,Intermediate Region Code,Date,Deaths,Cases,Recovered,Hospitalised
875,Bermuda,United Kingdom,32.3078,-64.7505,BMU,Northern America,0,2020-09-21,NaN,NaN,NaN,NaN
876,Bermuda,United Kingdom,32.3078,-64.7505,BMU,Northern America,0,2020-09-22,NaN,NaN,NaN,NaN

### Determine how many people are vaccinated in Gibraltar

In [16]:
# Filter Vaccinated DF Province/State to Gibraltar
vaccinated[vaccinated['Province/State'] == 'Gibraltar']

,Province/State,Country/Region,Lat,Long,ISO 3166-1 Alpha 3-Codes,Sub-region Name,Intermediate Region Code,Date,Vaccinated,First Dose,Second Dose
3792,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2020-01-22,0,0,0
3793,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2020-01-23,0,0,0
3794,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2020-01-24,0,0,0
3795,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2020-01-25,0,0,0
3796,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2020-01-26,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
4419,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2021-10-10,2431,2763,2431
4420,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2021-10-11,2954,3646,2954
4421,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2021-10-12,3368,4606,3368
4422,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2021-10-13,0,0,0
4423,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2021-10-14,0,0,0

### Create a new name DataFrame just for Gibraltar vaccinations

In [17]:
gibraltar_only = vaccinated[vaccinated['Province/State'] == 'Gibraltar']

In [18]:
gibraltar_only.head()

,Province/State,Country/Region,Lat,Long,ISO 3166-1 Alpha 3-Codes,Sub-region Name,Intermediate Region Code,Date,Vaccinated,First Dose,Second Dose
3792,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2020-01-22,0,0,0
3793,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2020-01-23,0,0,0
3794,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2020-01-24,0,0,0
3795,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2020-01-25,0,0,0
3796,Gibraltar,United Kingdom,36.1408,-5.3536,GIB,Southern Europe,0,2020-01-26,0,0,0

### Subset Gibraltar only vaccinations to Vaccinated, First Dose, Second Dose columns

In [19]:
# View columns in Gibraltar Only DF
gibraltar_only.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long',
       'ISO 3166-1 Alpha 3-Codes', 'Sub-region Name',
       'Intermediate Region Code', 'Date', 'Vaccinated', 'First Dose',
       'Second Dose'],
      dtype='object')

In [20]:
gibraltar_detail = gibraltar_only[['Vaccinated', 'First Dose', 'Second Dose']]

In [21]:
gibraltar_detail.head()

      Vaccinated  First Dose  Second Dose
3792           0           0            0
3793           0           0            0
3794           0           0            0
3795           0           0            0
3796           0           0            0

### Find the total number of Vaccinated in Gibraltar

In [22]:
gibraltar_detail['Vaccinated'].sum()

5606041

### Find the total number of First Doses in Gibraltar

In [23]:
gibraltar_detail['First Dose'].sum()

5870786

### Find total number of Second Doses in Gibraltar

In [24]:
gibraltar_detail['Second Dose'].sum()

5606041

# Week 3 Assignment

## Objective: identify area which has greatest number of people with 1st dose only

Approach:

- merge cases and vaccinated DataFrames
- view new DataFrame
- determine column names and data types
- convert data type of Date column from object to DateTime
- drop unnecessary columns
- determine number of cases across the UK
- use groupby and aggregate functions to calculate differences between first and second doses
- determine if there are differences over time between first and second dose applications

### Merge cases and vaccinated DataFrames

In [25]:
# Left DataFrame is vaccinated
# Merge on index

In [26]:
covid = pd.merge(vaccinated, cases, left_index=True, right_index=True)

In [27]:
covid.head()

,Province/State_x,Country/Region_x,Lat_x,Long_x,ISO 3166-1 Alpha 3-Codes_x,Sub-region Name_x,Intermediate Region Code_x,Date_x,Vaccinated,First Dose,...,Lat_y,Long_y,ISO 3166-1 Alpha 3-Codes_y,Sub-region Name_y,Intermediate Region Code_y,Date_y,Deaths,Cases,Recovered,Hospitalised
0,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-22,0,0,...,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-22,0.0,0.0,0.0,0.0
1,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-23,0,0,...,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-23,0.0,0.0,0.0,0.0
2,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-24,0,0,...,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-24,0.0,0.0,0.0,0.0
3,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-25,0,0,...,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-25,0.0,0.0,0.0,0.0
4,Anguilla,United Kingdom,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-26,0,0,...,18.2206,-63.0686,AIA,Latin America and the Caribbean,29,2020-01-26,0.0,0.0,0.0,0.0

- Merge duplicates columns common to both DFs
- Subset to drop duplicate columns

In [28]:
# View Covid column duplicates
covid.columns

Index(['Province/State_x', 'Country/Region_x', 'Lat_x', 'Long_x',
       'ISO 3166-1 Alpha 3-Codes_x', 'Sub-region Name_x',
       'Intermediate Region Code_x', 'Date_x', 'Vaccinated', 'First Dose',
       'Second Dose', 'Province/State_y', 'Country/Region_y', 'Lat_y',
       'Long_y', 'ISO 3166-1 Alpha 3-Codes_y', 'Sub-region Name_y',
       'Intermediate Region Code_y', 'Date_y', 'Deaths', 'Cases', 'Recovered',
       'Hospitalised'],
      dtype='object')

Create subsetted DataFrame DF called covid_info

In [29]:
covid_info = covid[['Province/State_x', 'Country/Region_x', 'Date_x', 'Vaccinated', 'First Dose',
       'Second Dose', 'Deaths', 'Cases', 'Recovered',
       'Hospitalised']]

In [30]:
# View covid_info
covid_info.head()

,Province/State_x,Country/Region_x,Date_x,Vaccinated,First Dose,Second Dose,Deaths,Cases,Recovered,Hospitalised
0,Anguilla,United Kingdom,2020-01-22,0,0,0,0.0,0.0,0.0,0.0
1,Anguilla,United Kingdom,2020-01-23,0,0,0,0.0,0.0,0.0,0.0
2,Anguilla,United Kingdom,2020-01-24,0,0,0,0.0,0.0,0.0,0.0
3,Anguilla,United Kingdom,2020-01-25,0,0,0,0.0,0.0,0.0,0.0
4,Anguilla,United Kingdom,2020-01-26,0,0,0,0.0,0.0,0.0,0.0

In [31]:
# Rename column lables to remove _x
covid_info.rename(columns = {'Province/State_x':'Province/State', 'Country/Region_x':'Country/Region', 'Date_x':'Date'}, inplace = True)

/Users/michellehalpin/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [32]:
# View covid_info
covid_info.head()

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Deaths,Cases,Recovered,Hospitalised
0,Anguilla,United Kingdom,2020-01-22,0,0,0,0.0,0.0,0.0,0.0
1,Anguilla,United Kingdom,2020-01-23,0,0,0,0.0,0.0,0.0,0.0
2,Anguilla,United Kingdom,2020-01-24,0,0,0,0.0,0.0,0.0,0.0
3,Anguilla,United Kingdom,2020-01-25,0,0,0,0.0,0.0,0.0,0.0
4,Anguilla,United Kingdom,2020-01-26,0,0,0,0.0,0.0,0.0,0.0

Sense check merged covid_info DataFrame

In [33]:
covid_info.shape

(7584, 10)

In [34]:
covid_info.dtypes

Province/State     object
Country/Region     object
Date               object
Vaccinated          int64
First Dose          int64
Second Dose         int64
Deaths            float64
Cases             float64
Recovered         float64
Hospitalised      float64
dtype: object

In [35]:
# Check covid_info for missing data
covid_info_na = covid_info[covid_info.isna().any(axis=1)]

In [36]:
covid_info_na

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Deaths,Cases,Recovered,Hospitalised
875,Bermuda,United Kingdom,2020-09-21,0,0,0,NaN,NaN,NaN,NaN
876,Bermuda,United Kingdom,2020-09-22,0,0,0,NaN,NaN,NaN,NaN

### Convert Date column from object to DateTime

Import DateTime module

In [37]:
import datetime

In [38]:
covid_info['Date'] =  pd.to_datetime(covid_info['Date'])

/var/folders/_7/y9fnwxrn44d7m__w6dc1vy4w0000gn/T/ipykernel_3944/2204218676.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid_info['Date'] =  pd.to_datetime(covid_info['Date'])

In [39]:
covid_info.dtypes

Province/State            object
Country/Region            object
Date              datetime64[ns]
Vaccinated                 int64
First Dose                 int64
Second Dose                int64
Deaths                   float64
Cases                    float64
Recovered                float64
Hospitalised             float64
dtype: object

### Drop unnecessary columns and group by Province / State dose totals

Group by province / state to sum Vaccinated, First Dose and Second Doses totals

In [40]:
covid_summary = covid_info.groupby('Province/State')[['Vaccinated', 'First Dose', 'Second Dose']].sum()

In [41]:
covid_summary

,Vaccinated,First Dose,Second Dose
Province/State,,,
Anguilla,4709072,4931470,4709072
Bermuda,2690908,2817981,2690908
British Virgin Islands,4933315,5166303,4933315
Cayman Islands,3363624,3522476,3363624
Channel Islands,3139385,3287646,3139385
Falkland Islands (Malvinas),3587869,3757307,3587869
Gibraltar,5606041,5870786,5606041
Isle of Man,4036345,4226984,4036345
Montserrat,5157560,5401128,5157560
Others,2466669,2583151,2466669
"Saint Helena, Ascension and Tristan da Cunha",2242421,2348310,2242421
Turks and Caicos Islands,2915136,3052822,2915136

Include Date column in Groupby()

In [42]:
covid_summary = covid_info.groupby(['Province/State', 'Date'])[['Vaccinated', 'First Dose', 'Second Dose']].sum()

In [43]:
covid_summary

                                     Vaccinated  First Dose  Second Dose
Province/State           Date
Anguilla                 2020-01-22           0           0            0
                         2020-01-23           0           0            0
                         2020-01-24           0           0            0
                         2020-01-25           0           0            0
                         2020-01-26           0           0            0
...                                         ...         ...          ...
Turks and Caicos Islands 2021-10-10        1264        1437         1264
                         2021-10-11        1536        1896         1536
                         2021-10-12        1751        2395         1751
                         2021-10-13           0           0            0
                         2021-10-14           0           0            0

[7584 rows x 3 columns]

Remove Date from Groupby as does not add value to analysis

In [44]:
covid_summary = covid_info.groupby('Province/State')[['Vaccinated', 'First Dose', 'Second Dose']].sum()

In [45]:
covid_summary

,Vaccinated,First Dose,Second Dose
Province/State,,,
Anguilla,4709072,4931470,4709072
Bermuda,2690908,2817981,2690908
British Virgin Islands,4933315,5166303,4933315
Cayman Islands,3363624,3522476,3363624
Channel Islands,3139385,3287646,3139385
Falkland Islands (Malvinas),3587869,3757307,3587869
Gibraltar,5606041,5870786,5606041
Isle of Man,4036345,4226984,4036345
Montserrat,5157560,5401128,5157560
Others,2466669,2583151,2466669
"Saint Helena, Ascension and Tristan da Cunha",2242421,2348310,2242421
Turks and Caicos Islands,2915136,3052822,2915136

Calculate difference between First Dose and Second Dose

In [46]:
# View covid_summary columns
covid_summary.columns

Index(['Vaccinated', 'First Dose', 'Second Dose'], dtype='object')

In [47]:
# Add columnn into covid_summary DataFrame to hold difference between first and second dose
covid_summary = pd.DataFrame(covid_summary, columns=['Vaccinated', 'First Dose', 'Second Dose', 'Dose Difference'])

In [48]:
covid_summary

,Vaccinated,First Dose,Second Dose,Dose Difference
Province/State,,,,
Anguilla,4709072,4931470,4709072,NaN
Bermuda,2690908,2817981,2690908,NaN
British Virgin Islands,4933315,5166303,4933315,NaN
Cayman Islands,3363624,3522476,3363624,NaN
Channel Islands,3139385,3287646,3139385,NaN
Falkland Islands (Malvinas),3587869,3757307,3587869,NaN
Gibraltar,5606041,5870786,5606041,NaN
Isle of Man,4036345,4226984,4036345,NaN
Montserrat,5157560,5401128,5157560,NaN
Others,2466669,2583151,2466669,NaN
"Saint Helena, Ascension and Tristan da Cunha",2242421,2348310,2242421,NaN
Turks and Caicos Islands,2915136,3052822,2915136,NaN

In [49]:
# Calculate numeric difference between First and Second doses
covid_summary['Dose Difference'] = covid_summary['First Dose'] - covid_summary['Second Dose']

In [50]:
covid_summary

,Vaccinated,First Dose,Second Dose,Dose Difference
Province/State,,,,
Anguilla,4709072,4931470,4709072,222398
Bermuda,2690908,2817981,2690908,127073
British Virgin Islands,4933315,5166303,4933315,232988
Cayman Islands,3363624,3522476,3363624,158852
Channel Islands,3139385,3287646,3139385,148261
Falkland Islands (Malvinas),3587869,3757307,3587869,169438
Gibraltar,5606041,5870786,5606041,264745
Isle of Man,4036345,4226984,4036345,190639
Montserrat,5157560,5401128,5157560,243568
Others,2466669,2583151,2466669,116482
"Saint Helena, Ascension and Tristan da Cunha",2242421,2348310,2242421,105889
Turks and Caicos Islands,2915136,3052822,2915136,137686

In [51]:
# Sort on Dose Difference
covid_summary.sort_values(by='Dose Difference', ascending=False)

,Vaccinated,First Dose,Second Dose,Dose Difference
Province/State,,,,
Gibraltar,5606041,5870786,5606041,264745
Montserrat,5157560,5401128,5157560,243568
British Virgin Islands,4933315,5166303,4933315,232988
Anguilla,4709072,4931470,4709072,222398
Isle of Man,4036345,4226984,4036345,190639
Falkland Islands (Malvinas),3587869,3757307,3587869,169438
Cayman Islands,3363624,3522476,3363624,158852
Channel Islands,3139385,3287646,3139385,148261
Turks and Caicos Islands,2915136,3052822,2915136,137686
Bermuda,2690908,2817981,2690908,127073
Others,2466669,2583151,2466669,116482
"Saint Helena, Ascension and Tristan da Cunha",2242421,2348310,2242421,105889

Dose difference as percentages

In [52]:
covid_summary['% Difference'] = 100 * covid_summary['Second Dose'] / covid_summary['First Dose']

In [53]:
covid_summary

,Vaccinated,First Dose,Second Dose,Dose Difference,% Difference
Province/State,,,,,
Anguilla,4709072,4931470,4709072,222398,95.490229
Bermuda,2690908,2817981,2690908,127073,95.490637
British Virgin Islands,4933315,5166303,4933315,232988,95.490237
Cayman Islands,3363624,3522476,3363624,158852,95.490331
Channel Islands,3139385,3287646,3139385,148261,95.490360
Falkland Islands (Malvinas),3587869,3757307,3587869,169438,95.490440
Gibraltar,5606041,5870786,5606041,264745,95.490468
Isle of Man,4036345,4226984,4036345,190639,95.489952
Montserrat,5157560,5401128,5157560,243568,95.490423
Others,2466669,2583151,2466669,116482,95.490701
"Saint Helena, Ascension and Tristan da Cunha",2242421,2348310,2242421,105889,95.490842
Turks and Caicos Islands,2915136,3052822,2915136,137686,95.489878

In [54]:
# Sort on percentage Difference
covid_summary.sort_values(by='% Difference', ascending=False)

,Vaccinated,First Dose,Second Dose,Dose Difference,% Difference
Province/State,,,,,
"Saint Helena, Ascension and Tristan da Cunha",2242421,2348310,2242421,105889,95.490842
Others,2466669,2583151,2466669,116482,95.490701
Bermuda,2690908,2817981,2690908,127073,95.490637
Gibraltar,5606041,5870786,5606041,264745,95.490468
Falkland Islands (Malvinas),3587869,3757307,3587869,169438,95.490440
Montserrat,5157560,5401128,5157560,243568,95.490423
Channel Islands,3139385,3287646,3139385,148261,95.490360
Cayman Islands,3363624,3522476,3363624,158852,95.490331
British Virgin Islands,4933315,5166303,4933315,232988,95.490237
Anguilla,4709072,4931470,4709072,222398,95.490229
Isle of Man,4036345,4226984,4036345,190639,95.489952
Turks and Caicos Islands,2915136,3052822,2915136,137686,95.489878

### How has the number of vaccinated individuals (first and second doses), changed over time?

Based on Gilbraltar data set only

In [55]:
covid_info.head()

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Deaths,Cases,Recovered,Hospitalised
0,Anguilla,United Kingdom,2020-01-22,0,0,0,0.0,0.0,0.0,0.0
1,Anguilla,United Kingdom,2020-01-23,0,0,0,0.0,0.0,0.0,0.0
2,Anguilla,United Kingdom,2020-01-24,0,0,0,0.0,0.0,0.0,0.0
3,Anguilla,United Kingdom,2020-01-25,0,0,0,0.0,0.0,0.0,0.0
4,Anguilla,United Kingdom,2020-01-26,0,0,0,0.0,0.0,0.0,0.0

In [56]:
# Filter covid_info into new DataFrame for Province/State Gibraltar only
covid_gibraltar = covid_info[covid_info['Province/State'] == 'Gibraltar']

In [57]:
covid_gibraltar

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Deaths,Cases,Recovered,Hospitalised
3792,Gibraltar,United Kingdom,2020-01-22,0,0,0,0.0,0.0,0.0,0.0
3793,Gibraltar,United Kingdom,2020-01-23,0,0,0,0.0,0.0,0.0,0.0
3794,Gibraltar,United Kingdom,2020-01-24,0,0,0,0.0,0.0,0.0,0.0
3795,Gibraltar,United Kingdom,2020-01-25,0,0,0,0.0,0.0,0.0,0.0
3796,Gibraltar,United Kingdom,2020-01-26,0,0,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
4419,Gibraltar,United Kingdom,2021-10-10,2431,2763,2431,97.0,5626.0,0.0,858.0
4420,Gibraltar,United Kingdom,2021-10-11,2954,3646,2954,97.0,5655.0,0.0,876.0
4421,Gibraltar,United Kingdom,2021-10-12,3368,4606,3368,97.0,5682.0,0.0,876.0
4422,Gibraltar,United Kingdom,2021-10-13,0,0,0,97.0,5707.0,0.0,0.0
4423,Gibraltar,United Kingdom,2021-10-14,0,0,0,97.0,5727.0,0.0,0.0

In [58]:
pd.set_option("display.max_rows", None)

In [59]:
covid_gibraltar

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Deaths,Cases,Recovered,Hospitalised
3792,Gibraltar,United Kingdom,2020-01-22,0,0,0,0.0,0.0,0.0,0.0
3793,Gibraltar,United Kingdom,2020-01-23,0,0,0,0.0,0.0,0.0,0.0
3794,Gibraltar,United Kingdom,2020-01-24,0,0,0,0.0,0.0,0.0,0.0
3795,Gibraltar,United Kingdom,2020-01-25,0,0,0,0.0,0.0,0.0,0.0
3796,Gibraltar,United Kingdom,2020-01-26,0,0,0,0.0,0.0,0.0,0.0
3797,Gibraltar,United Kingdom,2020-01-27,0,0,0,0.0,0.0,0.0,0.0
3798,Gibraltar,United Kingdom,2020-01-28,0,0,0,0.0,0.0,0.0,0.0
3799,Gibraltar,United Kingdom,2020-01-29,0,0,0,0.0,0.0,0.0,0.0
3800,Gibraltar,United Kingdom,2020-01-30,0,0,0,0.0,0.0,0.0,0.0
3801,Gibraltar,United Kingdom,2020-01-31,0,0,0,0.0,0.0,0.0,0.0
3802,Gibraltar,United Kingdom,2020-02-01,0,0,0,0.0,0.0,0.0,0.0
3803,Gibraltar,United Kingdom,2020-02-02,0,0,0,0.0,0.0,0.0,0.0
3804,Gibraltar,United Kingdom,2020-02-03,0,0,0,0.0,0.0,0.0,0.0
3805,Gibraltar,United Kingdom,2020-02-04,0,0,0,0.0,0.0,0.0,0.0
3806,Gibraltar,United Kingdom,2020-02-05,0,0,0,0.0,0.0,0.0,0.0
3807,Gibraltar,United Kingdom,2020-02-06,0,0,0,0.0,0.0,0.0,0.0
3808,Gibraltar,United Kingdom,2020-02-07,0,0,0,0.0,0.0,0.0,0.0
3809,Gibraltar,United Kingdom,2020-02-08,0,0,0,0.0,0.0,0.0,0.0
3810,Gibraltar,United Kingdom,2020-02-09,0,0,0,0.0,0.0,0.0,0.0
3811,Gibraltar,United Kingdom,2020-02-10,0,0,0,0.0,0.0,0.0,0.0
3812,Gibraltar,United Kingdom,2020-02-11,0,0,0,0.0,0.0,0.0,0.0
3813,Gibraltar,United Kingdom,2020-02-12,0,0,0,0.0,0.0,0.0,0.0
3814,Gibraltar,United Kingdom,2020-02-13,0,0,0,0.0,0.0,0.0,0.0
3815,Gibraltar,United Kingdom,2020-02-14,0,0,0,0.0,0.0,0.0,0.0
3816,Gibraltar,United Kingdom,2020-02-15,0,0,0,0.0,0.0,0.0,0.0
3817,Gibraltar,United Kingdom,2020-02-16,0,0,0,0.0,0.0,0.0,0.0
3818,Gibraltar,United Kingdom,2020-02-17,0,0,0,0.0,0.0,0.0,0.0
3819,Gibraltar,United Kingdom,2020-02-18,0,0,0,0.0,0.0,0.0,0.0
3820,Gibraltar,United Kingdom,2020-02-19,0,0,0,0.0,0.0,0.0,0.0
3821,Gibraltar,United Kingdom,2020-02-20,0,0,0,0.0,0.0,0.0,0.0
3822,Gibraltar,United Kingdom,2020-02-21,0,0,0,0.0,0.0,0.0,0.0
3823,Gibraltar,United Kingdom,2020-02-22,0,0,0,0.0,0.0,0.0,0.0
3824,Gibraltar,United Kingdom,2020-02-23,0,0,0,0.0,0.0,0.0,0.0
3825,Gibraltar,United Kingdom,2020-02-24,0,0,0,0.0,0.0,0.0,0.0
3826,Gibraltar,United Kingdom,2020-02-25,0,0,0,0.0,0.0,0.0,0.0
3827,Gibraltar,United Kingdom,2020-02-26,0,0,0,0.0,0.0,0.0,0.0
3828,Gibraltar,United Kingdom,2020-02-27,0,0,0,0.0,0.0,0.0,0.0
3829,Gibraltar,United Kingdom,2020-02-28,0,0,0,0.0,0.0,0.0,0.0
3830,Gibraltar,United Kingdom,2020-02-29,0,0,0,0.0,0.0,0.0,0.0
3831,Gibraltar,United Kingdom,2020-03-01,0,0,0,0.0,0.0,0.0,0.0
3832,Gibraltar,United Kingdom,2020-03-02,0,0,0,0.0,0.0,0.0,0.0
3833,Gibraltar,United Kingdom,2020-03-03,0,0,0,0.0,0.0,0.0,0.0
3834,Gibraltar,United Kingdom,2020-03-04,0,0,0,0.0,1.0,0.0,0.0
3835,Gibraltar,United Kingdom,2020-03-05,0,0,0,0.0,1.0,0.0,0.0
3836,Gibraltar,United Kingdom,2020-03-06,0,0,0,0.0,1.0,0.0,0.0
3837,Gibraltar,United Kingdom,2020-03-07,0,0,0,0.0,1.0,0.0,0.0
3838,Gibraltar,United Kingdom,2020-03-08,0,0,0,0.0,1.0,0.0,0.0
3839,Gibraltar,United Kingdom,2020-03-09,0,0,0,0.0,1.0,0.0,0.0
3840,Gibraltar,United Kingdom,2020-03-10,0,0,0,0.0,1.0,1.0,0.0
3841,Gibraltar,United Kingdom,2020-03-11,0,0,0,0.0,1.0,1.0,0.0
3842,Gibraltar,United Kingdom,2020-03-12,0,0,0,0.0,1.0,1.0,0.0
3843,Gibraltar,United Kingdom,2020-03-13,0,0,0,0.0,1.0,1.0,0.0
3844,Gibraltar,United Kingdom,2020-03-14,0,0,0,0.0,1.0,1.0,0.0
3845,Gibraltar,United Kingdom,2020-03-15,0,0,0,0.0,1.0,1.0,0.0
3846,Gibraltar,United Kingdom,2020-03-16,0,0,0,0.0,1.0,1.0,0.0
3847,Gibraltar,United Kingdom,2020-03-17,0,0,0,0.0,3.0,1.0,0.0
3848,Gibraltar,United Kingdom,2020-03-18,0,0,0,0.0,8.0,2.0,0.0
3849,Gibraltar,United Kingdom,2020-03-19,0,0,0,0.0,10.0,2.0,0.0
3850,Gibraltar,United Kingdom,2020-03-20,0,0,0,0.0,10.0,2.0,0.0
3851,Gibraltar,United Kingdom,2020-03-21,0,0,0,0.0,10.0,2.0,0.0
3852,Gibraltar,United Kingdom,2020-03-22,0,0,0,0.0,15.0,2.0,0.0
3853,Gibraltar,United Kingdom,2020-03-23,0,0,0,0.0,15.0,2.0,0.0
3854,Gibraltar,United Kingdom,2020-03-24,0,0,0,0.0,15.0,5.0,0.0
3855,Gibraltar,United Kingdom,2020-03-25,0,0,0,0.0,26.0,5.0,0.0
3856,Gibraltar,United Kingdom,2020-03-26,0,0,0,0.0,35.0,13.0,0.0
3857,Gibraltar,United Kingdom,2020-03-27,0,0,0,0.0,55.0,14.0,908.0
3858,Gibraltar,United Kingdom,2020-03-28,0,0,0,0.0,56.0,14.0,1035.0
3859,Gibraltar,United Kingdom,2020-03-29,0,0,0,0.0,65.0,14.0,1191.0
3860,Gibraltar,United Kingdom,2020-03-30,0,0,0,0.0,69.0,34.0,1387.0
3861,Gibraltar,United Kingdom,2020-03-31,0,0,0,0.0,69.0,34.0,1575.0
3862,Gibraltar,United Kingdom,2020-04-01,0,0,0,0.0,81.0,34.0,1705.0
3863,Gibraltar,United Kingdom,2020-04-02,0,0,0,0.0,88.0,46.0,1734.0
3864,Gibraltar,United Kingdom,2020-04-03,0,0,0,0.0,95.0,46.0,1943.0
3865,Gibraltar,United Kingdom,2020-04-04,0,0,0,0.0,98.0,52.0,2188.0
3866,Gibraltar,United Kingdom,2020-04-05,0,0,0,0.0,103.0,52.0,2357.0
3867,Gibraltar,United Kingdom,2020-04-06,0,0,0,0.0,109.0,52.0,2437.0
3868,Gibraltar,United Kingdom,2020-04-07,0,0,0,0.0,113.0,60.0,2529.0
3869,Gibraltar,United Kingdom,2020-04-08,0,0,0,0.0,120.0,60.0,2592.0
3870,Gibraltar,United Kingdom,2020-04-09,0,0,0,0.0,123.0,60.0,2626.0
3871,Gibraltar,United Kingdom,2020-04-10,0,0,0,0.0,127.0,69.0,2660.0
3872,Gibraltar,United Kingdom,2020-04-11,0,0,0,0.0,129.0,84.0,2657.0
3873,Gibraltar,United Kingdom,2020-04-12,0,0,0,0.0,129.0,84.0,2711.0
3874,Gibraltar,United Kingdom,2020-04-13,0,0,0,0.0,129.0,84.0,2664.0
3875,Gibraltar,United Kingdom,2020-04-14,0,0,0,0.0,129.0,93.0,2660.0
3876,Gibraltar,United Kingdom,2020-04-15,0,0,0,0.0,131.0,104.0,2573.0
3877,Gibraltar,United Kingdom,2020-04-16,0,0,0,0.0,131.0,104.0,2549.0
3878,Gibraltar,United Kingdom,2020-04-17,0,0,0,0.0,132.0,105.0,2416.0
3879,Gibraltar,United Kingdom,2020-04-18,0,0,0,0.0,132.0,111.0,2432.0
3880,Gibraltar,United Kingdom,2020-04-19,0,0,0,0.0,132.0,120.0,2447.0
3881,Gibraltar,United Kingdom,2020-04-20,0,0,0,0.0,132.0,120.0,2416.0
3882,Gibraltar,United Kingdom,2020-04-21,0,0,0,0.0,132.0,120.0,2392.0
3883,Gibraltar,United Kingdom,2020-04-22,0,0,0,0.0,132.0,127.0,2317.0
3884,Gibraltar,United Kingdom,2020-04-23,0,0,0,0.0,133.0,129.0,2233.0
3885,Gibraltar,United Kingdom,2020-04-24,0,0,0,0.0,133.0,131.0,2133.0
3886,Gibraltar,United Kingdom,2020-04-25,0,0,0,0.0,136.0,131.0,2076.0
3887,Gibraltar,United Kingdom,2020-04-26,0,0,0,0.0,141.0,131.0,2069.0
3888,Gibraltar,United Kingdom,2020-04-27,0,0,0,0.0,141.0,131.0,2083.0
3889,Gibraltar,United Kingdom,2020-04-28,0,0,0,0.0,141.0,131.0,1985.0
3890,Gibraltar,United Kingdom,2020-04-29,0,0,0,0.0,141.0,131.0,1940.0
3891,Gibraltar,United Kingdom,2020-04-30,0,0,0,0.0,144.0,131.0,1896.0
3892,Gibraltar,United Kingdom,2020-05-01,0,0,0,0.0,144.0,131.0,1840.0
3893,Gibraltar,United Kingdom,2020-05-02,0,0,0,0.0,144.0,132.0,1798.0
3894,Gibraltar,United Kingdom,2020-05-03,0,0,0,0.0,144.0,132.0,1774.0
3895,Gibraltar,United Kingdom,2020-05-04,0,0,0,0.0,144.0,133.0,1762.0
3896,Gibraltar,United Kingdom,2020-05-05,0,0,0,0.0,144.0,133.0,1715.0
3897,Gibraltar,United Kingdom,2020-05-06,0,0,0,0.0,144.0,136.0,1644.0
3898,Gibraltar,United Kingdom,2020-05-07,0,0,0,0.0,144.0,141.0,1578.0
3899,Gibraltar,United Kingdom,2020-05-08,0,0,0,0.0,146.0,142.0,1507.0
3900,Gibraltar,United Kingdom,2020-05-09,0,0,0,0.0,146.0,142.0,1502.0
3901,Gibraltar,United Kingdom,2020-05-10,0,0,0,0.0,146.0,143.0,1466.0
3902,Gibraltar,United Kingdom,2020-05-11,0,0,0,0.0,147.0,143.0,1496.0
3903,Gibraltar,United Kingdom,2020-05-12,0,0,0,0.0,148.0,144.0,1449.0
3904,Gibraltar,United Kingdom,2020-05-13,0,0,0,0.0,147.0,144.0,1418.0
3905,Gibraltar,United Kingdom,2020-05-14,0,0,0,0.0,147.0,144.0,1365.0
3906,Gibraltar,United Kingdom,2020-05-15,0,0,0,0.0,147.0,144.0,1336.0
3907,Gibraltar,United Kingdom,2020-05-16,0,0,0,0.0,147.0,145.0,1280.0
3908,Gibraltar,United Kingdom,2020-05-17,0,0,0,0.0,147.0,145.0,1275.0
3909,Gibraltar,United Kingdom,2020-05-18,0,0,0,0.0,147.0,145.0,1279.0
3910,Gibraltar,United Kingdom,2020-05-19,0,0,0,0.0,147.0,145.0,1252.0
3911,Gibraltar,United Kingdom,2020-05-20,0,0,0,0.0,149.0,145.0,1195.0
3912,Gibraltar,United Kingdom,2020-05-21,0,0,0,0.0,151.0,146.0,1162.0
3913,Gibraltar,United Kingdom,2020-05-22,0,0,0,0.0,151.0,147.0,1148.0
3914,Gibraltar,United Kingdom,2020-05-23,0,0,0,0.0,152.0,147.0,1102.0
3915,Gibraltar,United Kingdom,2020-05-24,0,0,0,0.0,154.0,147.0,1102.0
3916,Gibraltar,United Kingdom,2020-05-25,0,0,0,0.0,154.0,147.0,1104.0
3917,Gibraltar,United Kingdom,2020-05-26,0,0,0,0.0,154.0,147.0,1092.0
3918,Gibraltar,United Kingdom,2020-05-27,0,0,0,0.0,157.0,147.0,1028.0
3919,Gibraltar,United Kingdom,2020-05-28,0,0,0,0.0,158.0,147.0,988.0
3920,Gibraltar,United Kingdom,2020-05-29,0,0,0,0.0,161.0,148.0,948.0
3921,Gibraltar,United Kingdom,2020-05-30,0,0,0,0.0,169.0,149.0,908.0
3922,Gibraltar,United Kingdom,2020-05-31,0,0,0,0.0,170.0,149.0,905.0
3923,Gibraltar,United Kingdom,2020-06-01,0,0,0,0.0,170.0,151.0,906.0
3924,Gibraltar,United Kingdom,2020-06-02,0,0,0,0.0,172.0,151.0,886.0
3925,Gibraltar,United Kingdom,2020-06-03,0,0,0,0.0,173.0,153.0,852.0
3926,Gibraltar,United Kingdom,2020-06-04,0,0,0,0.0,173.0,153.0,822.0
3927,Gibraltar,United Kingdom,2020-06-05,0,0,0,0.0,174.0,153.0,797.0
3928,Gibraltar,United Kingdom,2020-06-06,0,0,0,0.0,175.0,155.0,769.0
3929,Gibraltar,United Kingdom,2020-06-07,0,0,0,0.0,176.0,164.0,743.0
3930,Gibraltar,United Kingdom,2020-06-08,0,0,0,0.0,176.0,165.0,741.0
3931,Gibraltar,United Kingdom,2020-06-09,0,0,0,0.0,176.0,165.0,717.0
3932,Gibraltar,United Kingdom,2020-06-10,0,0,0,0.0,176.0,169.0,684.0
3933,Gibraltar,United Kingdom,2020-06-11,0,0,0,0.0,176.0,171.0,647.0
3934,Gibraltar,United Kingdom,2020-06-12,0,0,0,0.0,176.0,172.0,636.0
3935,Gibraltar,United Kingdom,2020-06-13,0,0,0,0.0,176.0,173.0,618.0
3936,Gibraltar,United Kingdom,2020-06-14,0,0,0,0.0,176.0,173.0,614.0
3937,Gibraltar,United Kingdom,2020-06-15,0,0,0,0.0,176.0,174.0,609.0
3938,Gibraltar,United Kingdom,2020-06-16,0,0,0,0.0,176.0,174.0,608.0
3939,Gibraltar,United Kingdom,2020-06-17,0,0,0,0.0,176.0,176.0,590.0
3940,Gibraltar,United Kingdom,2020-06-18,0,0,0,0.0,176.0,176.0,570.0
3941,Gibraltar,United Kingdom,2020-06-19,0,0,0,0.0,176.0,176.0,552.0
3942,Gibraltar,United Kingdom,2020-06-20,0,0,0,0.0,176.0,176.0,532.0
3943,Gibraltar,United Kingdom,2020-06-21,0,0,0,0.0,176.0,176.0,528.0
3944,Gibraltar,United Kingdom,2020-06-22,0,0,0,0.0,176.0,176.0,535.0
3945,Gibraltar,United Kingdom,2020-06-23,0,0,0,0.0,176.0,176.0,517.0
3946,Gibraltar,United Kingdom,2020-06-24,0,0,0,0.0,176.0,176.0,504.0
3947,Gibraltar,United Kingdom,2020-06-25,0,0,0,0.0,176.0,176.0,481.0
3948,Gibraltar,United Kingdom,2020-06-26,0,0,0,0.0,176.0,176.0,452.0
3949,Gibraltar,United Kingdom,2020-06-27,0,0,0,0.0,177.0,176.0,443.0
3950,Gibraltar,United Kingdom,2020-06-28,0,0,0,0.0,177.0,176.0,445.0
3951,Gibraltar,United Kingdom,2020-06-29,0,0,0,0.0,177.0,176.0,468.0
3952,Gibraltar,United Kingdom,2020-06-30,0,0,0,0.0,177.0,176.0,423.0
3953,Gibraltar,United Kingdom,2020-07-01,0,0,0,0.0,178.0,176.0,400.0
3954,Gibraltar,United Kingdom,2020-07-02,0,0,0,0.0,178.0,176.0,385.0
3955,Gibraltar,United Kingdom,2020-07-03,0,0,0,0.0,178.0,176.0,368.0
3956,Gibraltar,United Kingdom,2020-07-04,0,0,0,0.0,178.0,176.0,350.0
3957,Gibraltar,United Kingdom,2020-07-05,0,0,0,0.0,179.0,176.0,343.0
3958,Gibraltar,United Kingdom,2020-07-06,0,0,0,0.0,179.0,176.0,337.0
3959,Gibraltar,United Kingdom,2020-07-07,0,0,0,0.0,179.0,176.0,325.0
3960,Gibraltar,United Kingdom,2020-07-08,0,0,0,0.0,179.0,176.0,307.0
3961,Gibraltar,United Kingdom,2020-07-09,0,0,0,0.0,180.0,176.0,293.0
3962,Gibraltar,United Kingdom,2020-07-10,0,0,0,0.0,180.0,176.0,280.0
3963,Gibraltar,United Kingdom,2020-07-11,0,0,0,0.0,180.0,176.0,265.0
3964,Gibraltar,United Kingdom,2020-07-12,0,0,0,0.0,180.0,176.0,263.0
3965,Gibraltar,United Kingdom,2020-07-13,0,0,0,0.0,180.0,179.0,264.0
3966,Gibraltar,United Kingdom,2020-07-14,0,0,0,0.0,180.0,179.0,249.0
3967,Gibraltar,United Kingdom,2020-07-15,0,0,0,0.0,180.0,180.0,247.0
3968,Gibraltar,United Kingdom,2020-07-16,0,0,0,0.0,180.0,180.0,229.0
3969,Gibraltar,United Kingdom,2020-07-17,0,0,0,0.0,180.0,180.0,226.0
3970,Gibraltar,United Kingdom,2020-07-18,0,0,0,0.0,180.0,180.0,222.0
3971,Gibraltar,United Kingdom,2020-07-19,0,0,0,0.0,180.0,180.0,218.0
3972,Gibraltar,United Kingdom,2020-07-20,0,0,0,0.0,180.0,180.0,217.0
3973,Gibraltar,United Kingdom,2020-07-21,0,0,0,0.0,180.0,180.0,204.0
3974,Gibraltar,United Kingdom,2020-07-22,0,0,0,0.0,182.0,180.0,218.0
3975,Gibraltar,United Kingdom,2020-07-23,0,0,0,0.0,184.0,180.0,192.0
3976,Gibraltar,United Kingdom,2020-07-24,0,0,0,0.0,184.0,180.0,182.0
3977,Gibraltar,United Kingdom,2020-07-25,0,0,0,0.0,185.0,180.0,175.0
3978,Gibraltar,United Kingdom,2020-07-26,0,0,0,0.0,185.0,180.0,173.0
3979,Gibraltar,United Kingdom,2020-07-27,0,0,0,0.0,185.0,180.0,171.0
3980,Gibraltar,United Kingdom,2020-07-28,0,0,0,0.0,186.0,180.0,171.0
3981,Gibraltar,United Kingdom,2020-07-29,0,0,0,0.0,186.0,180.0,169.0
3982,Gibraltar,United Kingdom,2020-07-30,0,0,0,0.0,187.0,180.0,164.0
3983,Gibraltar,United Kingdom,2020-07-31,0,0,0,0.0,187.0,181.0,158.0
3984,Gibraltar,United Kingdom,2020-08-01,0,0,0,0.0,188.0,182.0,161.0
3985,Gibraltar,United Kingdom,2020-08-02,0,0,0,0.0,188.0,183.0,157.0
3986,Gibraltar,United Kingdom,2020-08-03,0,0,0,0.0,188.0,183.0,156.0
3987,Gibraltar,United Kingdom,2020-08-04,0,0,0,0.0,189.0,183.0,152.0
3988,Gibraltar,United Kingdom,2020-08-05,0,0,0,0.0,189.0,183.0,150.0
3989,Gibraltar,United Kingdom,2020-08-06,0,0,0,0.0,190.0,184.0,144.0
3990,Gibraltar,United Kingdom,2020-08-07,0,0,0,0.0,190.0,184.0,137.0
3991,Gibraltar,United Kingdom,2020-08-08,0,0,0,0.0,197.0,184.0,128.0
3992,Gibraltar,United Kingdom,2020-08-09,0,0,0,0.0,201.0,186.0,123.0
3993,Gibraltar,United Kingdom,2020-08-10,0,0,0,0.0,201.0,186.0,136.0
3994,Gibraltar,United Kingdom,2020-08-11,0,0,0,0.0,202.0,187.0,130.0
3995,Gibraltar,United Kingdom,2020-08-12,0,0,0,0.0,203.0,187.0,126.0
3996,Gibraltar,United Kingdom,2020-08-13,0,0,0,0.0,205.0,188.0,126.0
3997,Gibraltar,United Kingdom,2020-08-14,0,0,0,0.0,206.0,188.0,124.0
3998,Gibraltar,United Kingdom,2020-08-15,0,0,0,0.0,209.0,190.0,122.0
3999,Gibraltar,United Kingdom,2020-08-16,0,0,0,0.0,215.0,190.0,122.0
4000,Gibraltar,United Kingdom,2020-08-17,0,0,0,0.0,217.0,194.0,123.0
4001,Gibraltar,United Kingdom,2020-08-18,0,0,0,0.0,222.0,195.0,119.0
4002,Gibraltar,United Kingdom,2020-08-19,0,0,0,0.0,223.0,197.0,116.0
4003,Gibraltar,United Kingdom,2020-08-20,0,0,0,0.0,229.0,200.0,114.0
4004,Gibraltar,United Kingdom,2020-08-21,0,0,0,0.0,231.0,200.0,111.0
4005,Gibraltar,United Kingdom,2020-08-22,0,0,0,0.0,239.0,201.0,118.0
4006,Gibraltar,United Kingdom,2020-08-23,0,0,0,0.0,246.0,201.0,109.0
4007,Gibraltar,United Kingdom,2020-08-24,0,0,0,0.0,248.0,203.0,110.0
4008,Gibraltar,United Kingdom,2020-08-25,0,0,0,0.0,256.0,203.0,106.0
4009,Gibraltar,United Kingdom,2020-08-26,0,0,0,0.0,270.0,203.0,104.0
4010,Gibraltar,United Kingdom,2020-08-27,0,0,0,0.0,272.0,216.0,105.0
4011,Gibraltar,United Kingdom,2020-08-28,0,0,0,0.0,274.0,221.0,102.0
4012,Gibraltar,United Kingdom,2020-08-29,0,0,0,0.0,275.0,226.0,104.0
4013,Gibraltar,United Kingdom,2020-08-30,0,0,0,0.0,285.0,228.0,104.0
4014,Gibraltar,United Kingdom,2020-08-31,0,0,0,0.0,288.0,232.0,107.0
4015,Gibraltar,United Kingdom,2020-09-01,0,0,0,0.0,290.0,237.0,108.0
4016,Gibraltar,United Kingdom,2020-09-02,0,0,0,0.0,295.0,240.0,100.0
4017,Gibraltar,United Kingdom,2020-09-03,0,0,0,0.0,298.0,246.0,102.0
4018,Gibraltar,United Kingdom,2020-09-04,0,0,0,0.0,305.0,248.0,102.0
4019,Gibraltar,United Kingdom,2020-09-05,0,0,0,0.0,312.0,255.0,102.0
4020,Gibraltar,United Kingdom,2020-09-06,0,0,0,0.0,315.0,273.0,102.0
4021,Gibraltar,United Kingdom,2020-09-07,0,0,0,0.0,315.0,273.0,113.0
4022,Gibraltar,United Kingdom,2020-09-08,0,0,0,0.0,320.0,276.0,112.0
4023,Gibraltar,United Kingdom,2020-09-09,0,0,0,0.0,322.0,277.0,116.0
4024,Gibraltar,United Kingdom,2020-09-10,0,0,0,0.0,323.0,287.0,118.0
4025,Gibraltar,United Kingdom,2020-09-11,0,0,0,0.0,323.0,289.0,96.0
4026,Gibraltar,United Kingdom,2020-09-12,0,0,0,0.0,327.0,294.0,102.0
4027,Gibraltar,United Kingdom,2020-09-13,0,0,0,0.0,330.0,298.0,105.0
4028,Gibraltar,United Kingdom,2020-09-14,0,0,0,0.0,330.0,303.0,123.0
4029,Gibraltar,United Kingdom,2020-09-15,0,0,0,0.0,334.0,307.0,133.0
4030,Gibraltar,United Kingdom,2020-09-16,0,0,0,0.0,340.0,309.0,138.0
4031,Gibraltar,United Kingdom,2020-09-17,0,0,0,0.0,343.0,313.0,145.0
4032,Gibraltar,United Kingdom,2020-09-18,0,0,0,0.0,346.0,315.0,153.0
4033,Gibraltar,United Kingdom,2020-09-19,0,0,0,0.0,350.0,322.0,162.0
4034,Gibraltar,United Kingdom,2020-09-20,0,0,0,0.0,350.0,323.0,175.0
4035,Gibraltar,United Kingdom,2020-09-21,0,0,0,0.0,350.0,323.0,195.0
4036,Gibraltar,United Kingdom,2020-09-22,0,0,0,0.0,355.0,323.0,204.0
4037,Gibraltar,United Kingdom,2020-09-23,0,0,0,0.0,357.0,324.0,216.0
4038,Gibraltar,United Kingdom,2020-09-24,0,0,0,0.0,361.0,331.0,231.0
4039,Gibraltar,United Kingdom,2020-09-25,0,0,0,0.0,364.0,333.0,252.0
4040,Gibraltar,United Kingdom,2020-09-26,0,0,0,0.0,372.0,335.0,254.0
4041,Gibraltar,United Kingdom,2020-09-27,0,0,0,0.0,379.0,341.0,274.0
4042,Gibraltar,United Kingdom,2020-09-28,0,0,0,0.0,382.0,341.0,300.0
4043,Gibraltar,United Kingdom,2020-09-29,0,0,0,0.0,391.0,342.0,302.0
4044,Gibraltar,United Kingdom,2020-09-30,0,0,0,0.0,396.0,344.0,316.0
4045,Gibraltar,United Kingdom,2020-10-01,0,0,0,0.0,410.0,349.0,324.0
4046,Gibraltar,United Kingdom,2020-10-02,0,0,0,0.0,416.0,351.0,340.0
4047,Gibraltar,United Kingdom,2020-10-03,0,0,0,0.0,428.0,358.0,358.0
4048,Gibraltar,United Kingdom,2020-10-04,0,0,0,0.0,432.0,360.0,382.0
4049,Gibraltar,United Kingdom,2020-10-05,0,0,0,0.0,432.0,363.0,421.0
4050,Gibraltar,United Kingdom,2020-10-06,0,0,0,0.0,437.0,368.0,455.0
4051,Gibraltar,United Kingdom,2020-10-07,0,0,0,0.0,445.0,376.0,487.0
4052,Gibraltar,United Kingdom,2020-10-08,0,0,0,0.0,452.0,386.0,511.0
4053,Gibraltar,United Kingdom,2020-10-09,0,0,0,0.0,468.0,398.0,521.0
4054,Gibraltar,United Kingdom,2020-10-10,0,0,0,0.0,476.0,405.0,545.0
4055,Gibraltar,United Kingdom,2020-10-11,0,0,0,0.0,485.0,413.0,584.0
4056,Gibraltar,United Kingdom,2020-10-12,0,0,0,0.0,486.0,419.0,620.0
4057,Gibraltar,United Kingdom,2020-10-13,0,0,0,0.0,499.0,424.0,662.0
4058,Gibraltar,United Kingdom,2020-10-14,0,0,0,0.0,516.0,435.0,700.0
4059,Gibraltar,United Kingdom,2020-10-15,0,0,0,0.0,531.0,439.0,742.0
4060,Gibraltar,United Kingdom,2020-10-16,0,0,0,0.0,544.0,441.0,787.0
4061,Gibraltar,United Kingdom,2020-10-17,0,0,0,0.0,558.0,449.0,818.0
4062,Gibraltar,United Kingdom,2020-10-18,0,0,0,0.0,571.0,455.0,854.0
4063,Gibraltar,United Kingdom,2020-10-19,0,0,0,0.0,577.0,462.0,917.0
4064,Gibraltar,United Kingdom,2020-10-20,0,0,0,0.0,608.0,471.0,982.0
4065,Gibraltar,United Kingdom,2020-10-21,0,0,0,0.0,621.0,481.0,1016.0
4066,Gibraltar,United Kingdom,2020-10-22,0,0,0,0.0,630.0,495.0,1039.0
4067,Gibraltar,United Kingdom,2020-10-23,0,0,0,0.0,641.0,500.0,1111.0
4068,Gibraltar,United Kingdom,2020-10-24,0,0,0,0.0,660.0,507.0,1158.0
4069,Gibraltar,United Kingdom,2020-10-25,0,0,0,0.0,667.0,516.0,1223.0
4070,Gibraltar,United Kingdom,2020-10-26,0,0,0,0.0,670.0,532.0,1264.0
4071,Gibraltar,United Kingdom,2020-10-27,0,0,0,0.0,679.0,547.0,1367.0
4072,Gibraltar,United Kingdom,2020-10-28,0,0,0,0.0,682.0,562.0,1429.0
4073,Gibraltar,United Kingdom,2020-10-29,0,0,0,0.0,688.0,584.0,1448.0
4074,Gibraltar,United Kingdom,2020-10-30,0,0,0,0.0,693.0,590.0,1474.0
4075,Gibraltar,United Kingdom,2020-10-31,0,0,0,0.0,697.0,618.0,1539.0
4076,Gibraltar,United Kingdom,2020-11-01,0,0,0,0.0,703.0,620.0,1529.0
4077,Gibraltar,United Kingdom,2020-11-02,0,0,0,0.0,707.0,629.0,1638.0
4078,Gibraltar,United Kingdom,2020-11-03,0,0,0,0.0,730.0,638.0,1719.0
4079,Gibraltar,United Kingdom,2020-11-04,0,0,0,0.0,743.0,650.0,1727.0
4080,Gibraltar,United Kingdom,2020-11-05,0,0,0,0.0,754.0,655.0,1724.0
4081,Gibraltar,United Kingdom,2020-11-06,0,0,0,0.0,770.0,673.0,1745.0
4082,Gibraltar,United Kingdom,2020-11-07,0,0,0,0.0,785.0,682.0,1789.0
4083,Gibraltar,United Kingdom,2020-11-08,0,0,0,0.0,793.0,685.0,1818.0
4084,Gibraltar,United Kingdom,2020-11-09,0,0,0,0.0,805.0,692.0,1893.0

In [60]:
# View covid_summary columns
covid_gibraltar.columns

Index(['Province/State', 'Country/Region', 'Date', 'Vaccinated', 'First Dose',
       'Second Dose', 'Deaths', 'Cases', 'Recovered', 'Hospitalised'],
      dtype='object')

In [61]:
# Add columnn into covid_gibraltar DataFrame to hold difference between first and second dose
covid_gibraltar = pd.DataFrame(covid_gibraltar, columns=['Province/State', 'Country/Region', 'Date', 'Vaccinated', 'First Dose',
       'Second Dose', 'Dose Difference', 'Deaths', 'Cases', 'Recovered', 'Hospitalised'])

In [62]:
covid_gibraltar.head()

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Dose Difference,Deaths,Cases,Recovered,Hospitalised
3792,Gibraltar,United Kingdom,2020-01-22,0,0,0,NaN,0.0,0.0,0.0,0.0
3793,Gibraltar,United Kingdom,2020-01-23,0,0,0,NaN,0.0,0.0,0.0,0.0
3794,Gibraltar,United Kingdom,2020-01-24,0,0,0,NaN,0.0,0.0,0.0,0.0
3795,Gibraltar,United Kingdom,2020-01-25,0,0,0,NaN,0.0,0.0,0.0,0.0
3796,Gibraltar,United Kingdom,2020-01-26,0,0,0,NaN,0.0,0.0,0.0,0.0

In [63]:
# Calculate numeric difference between First and Second doses
covid_gibraltar['Dose Difference'] = covid_gibraltar['First Dose'] - covid_gibraltar['Second Dose']

In [65]:
covid_gibraltar.head()

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Dose Difference,Deaths,Cases,Recovered,Hospitalised
3792,Gibraltar,United Kingdom,2020-01-22,0,0,0,0,0.0,0.0,0.0,0.0
3793,Gibraltar,United Kingdom,2020-01-23,0,0,0,0,0.0,0.0,0.0,0.0
3794,Gibraltar,United Kingdom,2020-01-24,0,0,0,0,0.0,0.0,0.0,0.0
3795,Gibraltar,United Kingdom,2020-01-25,0,0,0,0,0.0,0.0,0.0,0.0
3796,Gibraltar,United Kingdom,2020-01-26,0,0,0,0,0.0,0.0,0.0,0.0

In [66]:
covid_gibraltar['% Difference'] = 100 * covid_gibraltar['Second Dose'] / covid_gibraltar['First Dose']

In [68]:
covid_gibraltar.head()

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Dose Difference,Deaths,Cases,Recovered,Hospitalised,% Difference
3792,Gibraltar,United Kingdom,2020-01-22,0,0,0,0,0.0,0.0,0.0,0.0,NaN
3793,Gibraltar,United Kingdom,2020-01-23,0,0,0,0,0.0,0.0,0.0,0.0,NaN
3794,Gibraltar,United Kingdom,2020-01-24,0,0,0,0,0.0,0.0,0.0,0.0,NaN
3795,Gibraltar,United Kingdom,2020-01-25,0,0,0,0,0.0,0.0,0.0,0.0,NaN
3796,Gibraltar,United Kingdom,2020-01-26,0,0,0,0,0.0,0.0,0.0,0.0,NaN

In [69]:
covid_gibraltar.columns

Index(['Province/State', 'Country/Region', 'Date', 'Vaccinated', 'First Dose',
       'Second Dose', 'Dose Difference', 'Deaths', 'Cases', 'Recovered',
       'Hospitalised', '% Difference'],
      dtype='object')

In [70]:
# Reorder the columns
covid_gibraltar = pd.DataFrame(covid_gibraltar, columns=['Province/State', 'Country/Region', 'Date', 'Vaccinated', 'First Dose',
       'Second Dose', 'Dose Difference', '% Difference', 'Deaths', 'Cases', 'Recovered', 'Hospitalised'])

In [71]:
covid_gibraltar.head()

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Dose Difference,% Difference,Deaths,Cases,Recovered,Hospitalised
3792,Gibraltar,United Kingdom,2020-01-22,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3793,Gibraltar,United Kingdom,2020-01-23,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3794,Gibraltar,United Kingdom,2020-01-24,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3795,Gibraltar,United Kingdom,2020-01-25,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3796,Gibraltar,United Kingdom,2020-01-26,0,0,0,0,NaN,0.0,0.0,0.0,0.0

In [72]:
covid_gibraltar

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Dose Difference,% Difference,Deaths,Cases,Recovered,Hospitalised
3792,Gibraltar,United Kingdom,2020-01-22,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3793,Gibraltar,United Kingdom,2020-01-23,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3794,Gibraltar,United Kingdom,2020-01-24,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3795,Gibraltar,United Kingdom,2020-01-25,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3796,Gibraltar,United Kingdom,2020-01-26,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3797,Gibraltar,United Kingdom,2020-01-27,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3798,Gibraltar,United Kingdom,2020-01-28,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3799,Gibraltar,United Kingdom,2020-01-29,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3800,Gibraltar,United Kingdom,2020-01-30,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3801,Gibraltar,United Kingdom,2020-01-31,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3802,Gibraltar,United Kingdom,2020-02-01,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3803,Gibraltar,United Kingdom,2020-02-02,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3804,Gibraltar,United Kingdom,2020-02-03,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3805,Gibraltar,United Kingdom,2020-02-04,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3806,Gibraltar,United Kingdom,2020-02-05,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3807,Gibraltar,United Kingdom,2020-02-06,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3808,Gibraltar,United Kingdom,2020-02-07,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3809,Gibraltar,United Kingdom,2020-02-08,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3810,Gibraltar,United Kingdom,2020-02-09,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3811,Gibraltar,United Kingdom,2020-02-10,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3812,Gibraltar,United Kingdom,2020-02-11,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3813,Gibraltar,United Kingdom,2020-02-12,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3814,Gibraltar,United Kingdom,2020-02-13,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3815,Gibraltar,United Kingdom,2020-02-14,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3816,Gibraltar,United Kingdom,2020-02-15,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3817,Gibraltar,United Kingdom,2020-02-16,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3818,Gibraltar,United Kingdom,2020-02-17,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3819,Gibraltar,United Kingdom,2020-02-18,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3820,Gibraltar,United Kingdom,2020-02-19,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3821,Gibraltar,United Kingdom,2020-02-20,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3822,Gibraltar,United Kingdom,2020-02-21,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3823,Gibraltar,United Kingdom,2020-02-22,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3824,Gibraltar,United Kingdom,2020-02-23,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3825,Gibraltar,United Kingdom,2020-02-24,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3826,Gibraltar,United Kingdom,2020-02-25,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3827,Gibraltar,United Kingdom,2020-02-26,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3828,Gibraltar,United Kingdom,2020-02-27,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3829,Gibraltar,United Kingdom,2020-02-28,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3830,Gibraltar,United Kingdom,2020-02-29,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3831,Gibraltar,United Kingdom,2020-03-01,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3832,Gibraltar,United Kingdom,2020-03-02,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3833,Gibraltar,United Kingdom,2020-03-03,0,0,0,0,NaN,0.0,0.0,0.0,0.0
3834,Gibraltar,United Kingdom,2020-03-04,0,0,0,0,NaN,0.0,1.0,0.0,0.0
3835,Gibraltar,United Kingdom,2020-03-05,0,0,0,0,NaN,0.0,1.0,0.0,0.0
3836,Gibraltar,United Kingdom,2020-03-06,0,0,0,0,NaN,0.0,1.0,0.0,0.0
3837,Gibraltar,United Kingdom,2020-03-07,0,0,0,0,NaN,0.0,1.0,0.0,0.0
3838,Gibraltar,United Kingdom,2020-03-08,0,0,0,0,NaN,0.0,1.0,0.0,0.0
3839,Gibraltar,United Kingdom,2020-03-09,0,0,0,0,NaN,0.0,1.0,0.0,0.0
3840,Gibraltar,United Kingdom,2020-03-10,0,0,0,0,NaN,0.0,1.0,1.0,0.0
3841,Gibraltar,United Kingdom,2020-03-11,0,0,0,0,NaN,0.0,1.0,1.0,0.0
3842,Gibraltar,United Kingdom,2020-03-12,0,0,0,0,NaN,0.0,1.0,1.0,0.0
3843,Gibraltar,United Kingdom,2020-03-13,0,0,0,0,NaN,0.0,1.0,1.0,0.0
3844,Gibraltar,United Kingdom,2020-03-14,0,0,0,0,NaN,0.0,1.0,1.0,0.0
3845,Gibraltar,United Kingdom,2020-03-15,0,0,0,0,NaN,0.0,1.0,1.0,0.0
3846,Gibraltar,United Kingdom,2020-03-16,0,0,0,0,NaN,0.0,1.0,1.0,0.0
3847,Gibraltar,United Kingdom,2020-03-17,0,0,0,0,NaN,0.0,3.0,1.0,0.0
3848,Gibraltar,United Kingdom,2020-03-18,0,0,0,0,NaN,0.0,8.0,2.0,0.0
3849,Gibraltar,United Kingdom,2020-03-19,0,0,0,0,NaN,0.0,10.0,2.0,0.0
3850,Gibraltar,United Kingdom,2020-03-20,0,0,0,0,NaN,0.0,10.0,2.0,0.0
3851,Gibraltar,United Kingdom,2020-03-21,0,0,0,0,NaN,0.0,10.0,2.0,0.0
3852,Gibraltar,United Kingdom,2020-03-22,0,0,0,0,NaN,0.0,15.0,2.0,0.0
3853,Gibraltar,United Kingdom,2020-03-23,0,0,0,0,NaN,0.0,15.0,2.0,0.0
3854,Gibraltar,United Kingdom,2020-03-24,0,0,0,0,NaN,0.0,15.0,5.0,0.0
3855,Gibraltar,United Kingdom,2020-03-25,0,0,0,0,NaN,0.0,26.0,5.0,0.0
3856,Gibraltar,United Kingdom,2020-03-26,0,0,0,0,NaN,0.0,35.0,13.0,0.0
3857,Gibraltar,United Kingdom,2020-03-27,0,0,0,0,NaN,0.0,55.0,14.0,908.0
3858,Gibraltar,United Kingdom,2020-03-28,0,0,0,0,NaN,0.0,56.0,14.0,1035.0
3859,Gibraltar,United Kingdom,2020-03-29,0,0,0,0,NaN,0.0,65.0,14.0,1191.0
3860,Gibraltar,United Kingdom,2020-03-30,0,0,0,0,NaN,0.0,69.0,34.0,1387.0
3861,Gibraltar,United Kingdom,2020-03-31,0,0,0,0,NaN,0.0,69.0,34.0,1575.0
3862,Gibraltar,United Kingdom,2020-04-01,0,0,0,0,NaN,0.0,81.0,34.0,1705.0
3863,Gibraltar,United Kingdom,2020-04-02,0,0,0,0,NaN,0.0,88.0,46.0,1734.0
3864,Gibraltar,United Kingdom,2020-04-03,0,0,0,0,NaN,0.0,95.0,46.0,1943.0
3865,Gibraltar,United Kingdom,2020-04-04,0,0,0,0,NaN,0.0,98.0,52.0,2188.0
3866,Gibraltar,United Kingdom,2020-04-05,0,0,0,0,NaN,0.0,103.0,52.0,2357.0
3867,Gibraltar,United Kingdom,2020-04-06,0,0,0,0,NaN,0.0,109.0,52.0,2437.0
3868,Gibraltar,United Kingdom,2020-04-07,0,0,0,0,NaN,0.0,113.0,60.0,2529.0
3869,Gibraltar,United Kingdom,2020-04-08,0,0,0,0,NaN,0.0,120.0,60.0,2592.0
3870,Gibraltar,United Kingdom,2020-04-09,0,0,0,0,NaN,0.0,123.0,60.0,2626.0
3871,Gibraltar,United Kingdom,2020-04-10,0,0,0,0,NaN,0.0,127.0,69.0,2660.0
3872,Gibraltar,United Kingdom,2020-04-11,0,0,0,0,NaN,0.0,129.0,84.0,2657.0
3873,Gibraltar,United Kingdom,2020-04-12,0,0,0,0,NaN,0.0,129.0,84.0,2711.0
3874,Gibraltar,United Kingdom,2020-04-13,0,0,0,0,NaN,0.0,129.0,84.0,2664.0
3875,Gibraltar,United Kingdom,2020-04-14,0,0,0,0,NaN,0.0,129.0,93.0,2660.0
3876,Gibraltar,United Kingdom,2020-04-15,0,0,0,0,NaN,0.0,131.0,104.0,2573.0
3877,Gibraltar,United Kingdom,2020-04-16,0,0,0,0,NaN,0.0,131.0,104.0,2549.0
3878,Gibraltar,United Kingdom,2020-04-17,0,0,0,0,NaN,0.0,132.0,105.0,2416.0
3879,Gibraltar,United Kingdom,2020-04-18,0,0,0,0,NaN,0.0,132.0,111.0,2432.0
3880,Gibraltar,United Kingdom,2020-04-19,0,0,0,0,NaN,0.0,132.0,120.0,2447.0
3881,Gibraltar,United Kingdom,2020-04-20,0,0,0,0,NaN,0.0,132.0,120.0,2416.0
3882,Gibraltar,United Kingdom,2020-04-21,0,0,0,0,NaN,0.0,132.0,120.0,2392.0
3883,Gibraltar,United Kingdom,2020-04-22,0,0,0,0,NaN,0.0,132.0,127.0,2317.0
3884,Gibraltar,United Kingdom,2020-04-23,0,0,0,0,NaN,0.0,133.0,129.0,2233.0
3885,Gibraltar,United Kingdom,2020-04-24,0,0,0,0,NaN,0.0,133.0,131.0,2133.0
3886,Gibraltar,United Kingdom,2020-04-25,0,0,0,0,NaN,0.0,136.0,131.0,2076.0
3887,Gibraltar,United Kingdom,2020-04-26,0,0,0,0,NaN,0.0,141.0,131.0,2069.0
3888,Gibraltar,United Kingdom,2020-04-27,0,0,0,0,NaN,0.0,141.0,131.0,2083.0
3889,Gibraltar,United Kingdom,2020-04-28,0,0,0,0,NaN,0.0,141.0,131.0,1985.0
3890,Gibraltar,United Kingdom,2020-04-29,0,0,0,0,NaN,0.0,141.0,131.0,1940.0
3891,Gibraltar,United Kingdom,2020-04-30,0,0,0,0,NaN,0.0,144.0,131.0,1896.0
3892,Gibraltar,United Kingdom,2020-05-01,0,0,0,0,NaN,0.0,144.0,131.0,1840.0
3893,Gibraltar,United Kingdom,2020-05-02,0,0,0,0,NaN,0.0,144.0,132.0,1798.0
3894,Gibraltar,United Kingdom,2020-05-03,0,0,0,0,NaN,0.0,144.0,132.0,1774.0
3895,Gibraltar,United Kingdom,2020-05-04,0,0,0,0,NaN,0.0,144.0,133.0,1762.0
3896,Gibraltar,United Kingdom,2020-05-05,0,0,0,0,NaN,0.0,144.0,133.0,1715.0
3897,Gibraltar,United Kingdom,2020-05-06,0,0,0,0,NaN,0.0,144.0,136.0,1644.0
3898,Gibraltar,United Kingdom,2020-05-07,0,0,0,0,NaN,0.0,144.0,141.0,1578.0
3899,Gibraltar,United Kingdom,2020-05-08,0,0,0,0,NaN,0.0,146.0,142.0,1507.0
3900,Gibraltar,United Kingdom,2020-05-09,0,0,0,0,NaN,0.0,146.0,142.0,1502.0
3901,Gibraltar,United Kingdom,2020-05-10,0,0,0,0,NaN,0.0,146.0,143.0,1466.0
3902,Gibraltar,United Kingdom,2020-05-11,0,0,0,0,NaN,0.0,147.0,143.0,1496.0
3903,Gibraltar,United Kingdom,2020-05-12,0,0,0,0,NaN,0.0,148.0,144.0,1449.0
3904,Gibraltar,United Kingdom,2020-05-13,0,0,0,0,NaN,0.0,147.0,144.0,1418.0
3905,Gibraltar,United Kingdom,2020-05-14,0,0,0,0,NaN,0.0,147.0,144.0,1365.0
3906,Gibraltar,United Kingdom,2020-05-15,0,0,0,0,NaN,0.0,147.0,144.0,1336.0
3907,Gibraltar,United Kingdom,2020-05-16,0,0,0,0,NaN,0.0,147.0,145.0,1280.0
3908,Gibraltar,United Kingdom,2020-05-17,0,0,0,0,NaN,0.0,147.0,145.0,1275.0
3909,Gibraltar,United Kingdom,2020-05-18,0,0,0,0,NaN,0.0,147.0,145.0,1279.0
3910,Gibraltar,United Kingdom,2020-05-19,0,0,0,0,NaN,0.0,147.0,145.0,1252.0
3911,Gibraltar,United Kingdom,2020-05-20,0,0,0,0,NaN,0.0,149.0,145.0,1195.0
3912,Gibraltar,United Kingdom,2020-05-21,0,0,0,0,NaN,0.0,151.0,146.0,1162.0
3913,Gibraltar,United Kingdom,2020-05-22,0,0,0,0,NaN,0.0,151.0,147.0,1148.0
3914,Gibraltar,United Kingdom,2020-05-23,0,0,0,0,NaN,0.0,152.0,147.0,1102.0
3915,Gibraltar,United Kingdom,2020-05-24,0,0,0,0,NaN,0.0,154.0,147.0,1102.0
3916,Gibraltar,United Kingdom,2020-05-25,0,0,0,0,NaN,0.0,154.0,147.0,1104.0
3917,Gibraltar,United Kingdom,2020-05-26,0,0,0,0,NaN,0.0,154.0,147.0,1092.0
3918,Gibraltar,United Kingdom,2020-05-27,0,0,0,0,NaN,0.0,157.0,147.0,1028.0
3919,Gibraltar,United Kingdom,2020-05-28,0,0,0,0,NaN,0.0,158.0,147.0,988.0
3920,Gibraltar,United Kingdom,2020-05-29,0,0,0,0,NaN,0.0,161.0,148.0,948.0
3921,Gibraltar,United Kingdom,2020-05-30,0,0,0,0,NaN,0.0,169.0,149.0,908.0
3922,Gibraltar,United Kingdom,2020-05-31,0,0,0,0,NaN,0.0,170.0,149.0,905.0
3923,Gibraltar,United Kingdom,2020-06-01,0,0,0,0,NaN,0.0,170.0,151.0,906.0
3924,Gibraltar,United Kingdom,2020-06-02,0,0,0,0,NaN,0.0,172.0,151.0,886.0
3925,Gibraltar,United Kingdom,2020-06-03,0,0,0,0,NaN,0.0,173.0,153.0,852.0
3926,Gibraltar,United Kingdom,2020-06-04,0,0,0,0,NaN,0.0,173.0,153.0,822.0
3927,Gibraltar,United Kingdom,2020-06-05,0,0,0,0,NaN,0.0,174.0,153.0,797.0
3928,Gibraltar,United Kingdom,2020-06-06,0,0,0,0,NaN,0.0,175.0,155.0,769.0
3929,Gibraltar,United Kingdom,2020-06-07,0,0,0,0,NaN,0.0,176.0,164.0,743.0
3930,Gibraltar,United Kingdom,2020-06-08,0,0,0,0,NaN,0.0,176.0,165.0,741.0
3931,Gibraltar,United Kingdom,2020-06-09,0,0,0,0,NaN,0.0,176.0,165.0,717.0
3932,Gibraltar,United Kingdom,2020-06-10,0,0,0,0,NaN,0.0,176.0,169.0,684.0
3933,Gibraltar,United Kingdom,2020-06-11,0,0,0,0,NaN,0.0,176.0,171.0,647.0
3934,Gibraltar,United Kingdom,2020-06-12,0,0,0,0,NaN,0.0,176.0,172.0,636.0
3935,Gibraltar,United Kingdom,2020-06-13,0,0,0,0,NaN,0.0,176.0,173.0,618.0
3936,Gibraltar,United Kingdom,2020-06-14,0,0,0,0,NaN,0.0,176.0,173.0,614.0
3937,Gibraltar,United Kingdom,2020-06-15,0,0,0,0,NaN,0.0,176.0,174.0,609.0
3938,Gibraltar,United Kingdom,2020-06-16,0,0,0,0,NaN,0.0,176.0,174.0,608.0
3939,Gibraltar,United Kingdom,2020-06-17,0,0,0,0,NaN,0.0,176.0,176.0,590.0
3940,Gibraltar,United Kingdom,2020-06-18,0,0,0,0,NaN,0.0,176.0,176.0,570.0
3941,Gibraltar,United Kingdom,2020-06-19,0,0,0,0,NaN,0.0,176.0,176.0,552.0
3942,Gibraltar,United Kingdom,2020-06-20,0,0,0,0,NaN,0.0,176.0,176.0,532.0
3943,Gibraltar,United Kingdom,2020-06-21,0,0,0,0,NaN,0.0,176.0,176.0,528.0
3944,Gibraltar,United Kingdom,2020-06-22,0,0,0,0,NaN,0.0,176.0,176.0,535.0
3945,Gibraltar,United Kingdom,2020-06-23,0,0,0,0,NaN,0.0,176.0,176.0,517.0
3946,Gibraltar,United Kingdom,2020-06-24,0,0,0,0,NaN,0.0,176.0,176.0,504.0
3947,Gibraltar,United Kingdom,2020-06-25,0,0,0,0,NaN,0.0,176.0,176.0,481.0
3948,Gibraltar,United Kingdom,2020-06-26,0,0,0,0,NaN,0.0,176.0,176.0,452.0
3949,Gibraltar,United Kingdom,2020-06-27,0,0,0,0,NaN,0.0,177.0,176.0,443.0
3950,Gibraltar,United Kingdom,2020-06-28,0,0,0,0,NaN,0.0,177.0,176.0,445.0
3951,Gibraltar,United Kingdom,2020-06-29,0,0,0,0,NaN,0.0,177.0,176.0,468.0
3952,Gibraltar,United Kingdom,2020-06-30,0,0,0,0,NaN,0.0,177.0,176.0,423.0
3953,Gibraltar,United Kingdom,2020-07-01,0,0,0,0,NaN,0.0,178.0,176.0,400.0
3954,Gibraltar,United Kingdom,2020-07-02,0,0,0,0,NaN,0.0,178.0,176.0,385.0
3955,Gibraltar,United Kingdom,2020-07-03,0,0,0,0,NaN,0.0,178.0,176.0,368.0
3956,Gibraltar,United Kingdom,2020-07-04,0,0,0,0,NaN,0.0,178.0,176.0,350.0
3957,Gibraltar,United Kingdom,2020-07-05,0,0,0,0,NaN,0.0,179.0,176.0,343.0
3958,Gibraltar,United Kingdom,2020-07-06,0,0,0,0,NaN,0.0,179.0,176.0,337.0
3959,Gibraltar,United Kingdom,2020-07-07,0,0,0,0,NaN,0.0,179.0,176.0,325.0
3960,Gibraltar,United Kingdom,2020-07-08,0,0,0,0,NaN,0.0,179.0,176.0,307.0
3961,Gibraltar,United Kingdom,2020-07-09,0,0,0,0,NaN,0.0,180.0,176.0,293.0
3962,Gibraltar,United Kingdom,2020-07-10,0,0,0,0,NaN,0.0,180.0,176.0,280.0
3963,Gibraltar,United Kingdom,2020-07-11,0,0,0,0,NaN,0.0,180.0,176.0,265.0
3964,Gibraltar,United Kingdom,2020-07-12,0,0,0,0,NaN,0.0,180.0,176.0,263.0
3965,Gibraltar,United Kingdom,2020-07-13,0,0,0,0,NaN,0.0,180.0,179.0,264.0
3966,Gibraltar,United Kingdom,2020-07-14,0,0,0,0,NaN,0.0,180.0,179.0,249.0
3967,Gibraltar,United Kingdom,2020-07-15,0,0,0,0,NaN,0.0,180.0,180.0,247.0
3968,Gibraltar,United Kingdom,2020-07-16,0,0,0,0,NaN,0.0,180.0,180.0,229.0
3969,Gibraltar,United Kingdom,2020-07-17,0,0,0,0,NaN,0.0,180.0,180.0,226.0
3970,Gibraltar,United Kingdom,2020-07-18,0,0,0,0,NaN,0.0,180.0,180.0,222.0
3971,Gibraltar,United Kingdom,2020-07-19,0,0,0,0,NaN,0.0,180.0,180.0,218.0
3972,Gibraltar,United Kingdom,2020-07-20,0,0,0,0,NaN,0.0,180.0,180.0,217.0
3973,Gibraltar,United Kingdom,2020-07-21,0,0,0,0,NaN,0.0,180.0,180.0,204.0
3974,Gibraltar,United Kingdom,2020-07-22,0,0,0,0,NaN,0.0,182.0,180.0,218.0
3975,Gibraltar,United Kingdom,2020-07-23,0,0,0,0,NaN,0.0,184.0,180.0,192.0
3976,Gibraltar,United Kingdom,2020-07-24,0,0,0,0,NaN,0.0,184.0,180.0,182.0
3977,Gibraltar,United Kingdom,2020-07-25,0,0,0,0,NaN,0.0,185.0,180.0,175.0
3978,Gibraltar,United Kingdom,2020-07-26,0,0,0,0,NaN,0.0,185.0,180.0,173.0
3979,Gibraltar,United Kingdom,2020-07-27,0,0,0,0,NaN,0.0,185.0,180.0,171.0
3980,Gibraltar,United Kingdom,2020-07-28,0,0,0,0,NaN,0.0,186.0,180.0,171.0
3981,Gibraltar,United Kingdom,2020-07-29,0,0,0,0,NaN,0.0,186.0,180.0,169.0
3982,Gibraltar,United Kingdom,2020-07-30,0,0,0,0,NaN,0.0,187.0,180.0,164.0
3983,Gibraltar,United Kingdom,2020-07-31,0,0,0,0,NaN,0.0,187.0,181.0,158.0
3984,Gibraltar,United Kingdom,2020-08-01,0,0,0,0,NaN,0.0,188.0,182.0,161.0
3985,Gibraltar,United Kingdom,2020-08-02,0,0,0,0,NaN,0.0,188.0,183.0,157.0
3986,Gibraltar,United Kingdom,2020-08-03,0,0,0,0,NaN,0.0,188.0,183.0,156.0
3987,Gibraltar,United Kingdom,2020-08-04,0,0,0,0,NaN,0.0,189.0,183.0,152.0
3988,Gibraltar,United Kingdom,2020-08-05,0,0,0,0,NaN,0.0,189.0,183.0,150.0
3989,Gibraltar,United Kingdom,2020-08-06,0,0,0,0,NaN,0.0,190.0,184.0,144.0
3990,Gibraltar,United Kingdom,2020-08-07,0,0,0,0,NaN,0.0,190.0,184.0,137.0
3991,Gibraltar,United Kingdom,2020-08-08,0,0,0,0,NaN,0.0,197.0,184.0,128.0
3992,Gibraltar,United Kingdom,2020-08-09,0,0,0,0,NaN,0.0,201.0,186.0,123.0
3993,Gibraltar,United Kingdom,2020-08-10,0,0,0,0,NaN,0.0,201.0,186.0,136.0
3994,Gibraltar,United Kingdom,2020-08-11,0,0,0,0,NaN,0.0,202.0,187.0,130.0
3995,Gibraltar,United Kingdom,2020-08-12,0,0,0,0,NaN,0.0,203.0,187.0,126.0
3996,Gibraltar,United Kingdom,2020-08-13,0,0,0,0,NaN,0.0,205.0,188.0,126.0
3997,Gibraltar,United Kingdom,2020-08-14,0,0,0,0,NaN,0.0,206.0,188.0,124.0
3998,Gibraltar,United Kingdom,2020-08-15,0,0,0,0,NaN,0.0,209.0,190.0,122.0
3999,Gibraltar,United Kingdom,2020-08-16,0,0,0,0,NaN,0.0,215.0,190.0,122.0
4000,Gibraltar,United Kingdom,2020-08-17,0,0,0,0,NaN,0.0,217.0,194.0,123.0
4001,Gibraltar,United Kingdom,2020-08-18,0,0,0,0,NaN,0.0,222.0,195.0,119.0
4002,Gibraltar,United Kingdom,2020-08-19,0,0,0,0,NaN,0.0,223.0,197.0,116.0
4003,Gibraltar,United Kingdom,2020-08-20,0,0,0,0,NaN,0.0,229.0,200.0,114.0
4004,Gibraltar,United Kingdom,2020-08-21,0,0,0,0,NaN,0.0,231.0,200.0,111.0
4005,Gibraltar,United Kingdom,2020-08-22,0,0,0,0,NaN,0.0,239.0,201.0,118.0
4006,Gibraltar,United Kingdom,2020-08-23,0,0,0,0,NaN,0.0,246.0,201.0,109.0
4007,Gibraltar,United Kingdom,2020-08-24,0,0,0,0,NaN,0.0,248.0,203.0,110.0
4008,Gibraltar,United Kingdom,2020-08-25,0,0,0,0,NaN,0.0,256.0,203.0,106.0
4009,Gibraltar,United Kingdom,2020-08-26,0,0,0,0,NaN,0.0,270.0,203.0,104.0
4010,Gibraltar,United Kingdom,2020-08-27,0,0,0,0,NaN,0.0,272.0,216.0,105.0
4011,Gibraltar,United Kingdom,2020-08-28,0,0,0,0,NaN,0.0,274.0,221.0,102.0
4012,Gibraltar,United Kingdom,2020-08-29,0,0,0,0,NaN,0.0,275.0,226.0,104.0
4013,Gibraltar,United Kingdom,2020-08-30,0,0,0,0,NaN,0.0,285.0,228.0,104.0
4014,Gibraltar,United Kingdom,2020-08-31,0,0,0,0,NaN,0.0,288.0,232.0,107.0
4015,Gibraltar,United Kingdom,2020-09-01,0,0,0,0,NaN,0.0,290.0,237.0,108.0
4016,Gibraltar,United Kingdom,2020-09-02,0,0,0,0,NaN,0.0,295.0,240.0,100.0
4017,Gibraltar,United Kingdom,2020-09-03,0,0,0,0,NaN,0.0,298.0,246.0,102.0
4018,Gibraltar,United Kingdom,2020-09-04,0,0,0,0,NaN,0.0,305.0,248.0,102.0
4019,Gibraltar,United Kingdom,2020-09-05,0,0,0,0,NaN,0.0,312.0,255.0,102.0
4020,Gibraltar,United Kingdom,2020-09-06,0,0,0,0,NaN,0.0,315.0,273.0,102.0
4021,Gibraltar,United Kingdom,2020-09-07,0,0,0,0,NaN,0.0,315.0,273.0,113.0
4022,Gibraltar,United Kingdom,2020-09-08,0,0,0,0,NaN,0.0,320.0,276.0,112.0
4023,Gibraltar,United Kingdom,2020-09-09,0,0,0,0,NaN,0.0,322.0,277.0,116.0
4024,Gibraltar,United Kingdom,2020-09-10,0,0,0,0,NaN,0.0,323.0,287.0,118.0
4025,Gibraltar,United Kingdom,2020-09-11,0,0,0,0,NaN,0.0,323.0,289.0,96.0
4026,Gibraltar,United Kingdom,2020-09-12,0,0,0,0,NaN,0.0,327.0,294.0,102.0
4027,Gibraltar,United Kingdom,2020-09-13,0,0,0,0,NaN,0.0,330.0,298.0,105.0
4028,Gibraltar,United Kingdom,2020-09-14,0,0,0,0,NaN,0.0,330.0,303.0,123.0
4029,Gibraltar,United Kingdom,2020-09-15,0,0,0,0,NaN,0.0,334.0,307.0,133.0
4030,Gibraltar,United Kingdom,2020-09-16,0,0,0,0,NaN,0.0,340.0,309.0,138.0
4031,Gibraltar,United Kingdom,2020-09-17,0,0,0,0,NaN,0.0,343.0,313.0,145.0
4032,Gibraltar,United Kingdom,2020-09-18,0,0,0,0,NaN,0.0,346.0,315.0,153.0
4033,Gibraltar,United Kingdom,2020-09-19,0,0,0,0,NaN,0.0,350.0,322.0,162.0
4034,Gibraltar,United Kingdom,2020-09-20,0,0,0,0,NaN,0.0,350.0,323.0,175.0
4035,Gibraltar,United Kingdom,2020-09-21,0,0,0,0,NaN,0.0,350.0,323.0,195.0
4036,Gibraltar,United Kingdom,2020-09-22,0,0,0,0,NaN,0.0,355.0,323.0,204.0
4037,Gibraltar,United Kingdom,2020-09-23,0,0,0,0,NaN,0.0,357.0,324.0,216.0
4038,Gibraltar,United Kingdom,2020-09-24,0,0,0,0,NaN,0.0,361.0,331.0,231.0
4039,Gibraltar,United Kingdom,2020-09-25,0,0,0,0,NaN,0.0,364.0,333.0,252.0
4040,Gibraltar,United Kingdom,2020-09-26,0,0,0,0,NaN,0.0,372.0,335.0,254.0
4041,Gibraltar,United Kingdom,2020-09-27,0,0,0,0,NaN,0.0,379.0,341.0,274.0
4042,Gibraltar,United Kingdom,2020-09-28,0,0,0,0,NaN,0.0,382.0,341.0,300.0
4043,Gibraltar,United Kingdom,2020-09-29,0,0,0,0,NaN,0.0,391.0,342.0,302.0
4044,Gibraltar,United Kingdom,2020-09-30,0,0,0,0,NaN,0.0,396.0,344.0,316.0
4045,Gibraltar,United Kingdom,2020-10-01,0,0,0,0,NaN,0.0,410.0,349.0,324.0
4046,Gibraltar,United Kingdom,2020-10-02,0,0,0,0,NaN,0.0,416.0,351.0,340.0
4047,Gibraltar,United Kingdom,2020-10-03,0,0,0,0,NaN,0.0,428.0,358.0,358.0
4048,Gibraltar,United Kingdom,2020-10-04,0,0,0,0,NaN,0.0,432.0,360.0,382.0
4049,Gibraltar,United Kingdom,2020-10-05,0,0,0,0,NaN,0.0,432.0,363.0,421.0
4050,Gibraltar,United Kingdom,2020-10-06,0,0,0,0,NaN,0.0,437.0,368.0,455.0
4051,Gibraltar,United Kingdom,2020-10-07,0,0,0,0,NaN,0.0,445.0,376.0,487.0
4052,Gibraltar,United Kingdom,2020-10-08,0,0,0,0,NaN,0.0,452.0,386.0,511.0
4053,Gibraltar,United Kingdom,2020-10-09,0,0,0,0,NaN,0.0,468.0,398.0,521.0
4054,Gibraltar,United Kingdom,2020-10-10,0,0,0,0,NaN,0.0,476.0,405.0,545.0
4055,Gibraltar,United Kingdom,2020-10-11,0,0,0,0,NaN,0.0,485.0,413.0,584.0
4056,Gibraltar,United Kingdom,2020-10-12,0,0,0,0,NaN,0.0,486.0,419.0,620.0
4057,Gibraltar,United Kingdom,2020-10-13,0,0,0,0,NaN,0.0,499.0,424.0,662.0
4058,Gibraltar,United Kingdom,2020-10-14,0,0,0,0,NaN,0.0,516.0,435.0,700.0
4059,Gibraltar,United Kingdom,2020-10-15,0,0,0,0,NaN,0.0,531.0,439.0,742.0
4060,Gibraltar,United Kingdom,2020-10-16,0,0,0,0,NaN,0.0,544.0,441.0,787.0

In [73]:
# Replace NaNs with a zero
covid_gibraltar['% Difference'] = covid_gibraltar['% Difference'].fillna(0)

In [74]:
covid_gibraltar.head()

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Dose Difference,% Difference,Deaths,Cases,Recovered,Hospitalised
3792,Gibraltar,United Kingdom,2020-01-22,0,0,0,0,0.0,0.0,0.0,0.0,0.0
3793,Gibraltar,United Kingdom,2020-01-23,0,0,0,0,0.0,0.0,0.0,0.0,0.0
3794,Gibraltar,United Kingdom,2020-01-24,0,0,0,0,0.0,0.0,0.0,0.0,0.0
3795,Gibraltar,United Kingdom,2020-01-25,0,0,0,0,0.0,0.0,0.0,0.0,0.0
3796,Gibraltar,United Kingdom,2020-01-26,0,0,0,0,0.0,0.0,0.0,0.0,0.0

### Max number of first dose

In [78]:
covid_gibraltar['First Dose'].max()

94038

In [81]:
# When did the max first dose occur?
mx_doses = covid_gibraltar[covid_gibraltar['First Dose']==94038]

In [82]:
print(covid_gibraltar['First Dose'].max())

94038

In [83]:
mx_doses

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Dose Difference,% Difference,Deaths,Cases,Recovered,Hospitalised
4215,Gibraltar,United Kingdom,2021-03-20,11497,94038,11497,82541,12.225909,94.0,4270.0,4148.0,696.0

In [84]:
covid_gibraltar.describe()

,Vaccinated,First Dose,Second Dose,Dose Difference,% Difference,Deaths,Cases,Recovered,Hospitalised
count,632.000000,632.000000,632.000000,632.000000,632.000000,632.000000,632.000000,632.000000,632.000000
mean,8870.318038,9289.218354,8870.318038,418.900316,83.521211,40.208861,2237.109177,1512.821203,1027.625000
std,15439.487761,16287.230372,15439.487761,18579.415986,139.587114,45.332832,2136.268090,1817.096755,1145.681058
min,0.000000,0.000000,0.000000,-49858.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,-3514.500000,0.000000,0.000000,177.000000,109.500000,157.750000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,1036.500000,323.500000,675.500000
75%,14594.000000,12488.750000,14594.000000,0.000000,143.002408,94.000000,4286.000000,4122.500000,1548.000000
max,69619.000000,94038.000000,69619.000000,82541.000000,708.754949,97.000000,5727.000000,4670.000000,4907.000000

In [85]:
# When did max second dose occur?
mx_sec_doses = covid_gibraltar[covid_gibraltar['Second Dose']==69619]

In [86]:
mx_sec_doses

,Province/State,Country/Region,Date,Vaccinated,First Dose,Second Dose,Dose Difference,% Difference,Deaths,Cases,Recovered,Hospitalised
4278,Gibraltar,United Kingdom,2021-05-22,69619,25676,69619,-43943,271.144259,94.0,4287.0,4192.0,111.0